name: CapyActions 😎

on:
  pull_request: {}
  push: { branches: [main] }

jobs:
  readmeWorkflow:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v3.1
        with:
          unityVersion: 2021.3.16f1

      # Output
      - uses: actions/upload-artifact@v3.1.3
        with:
          name: Build
          path: build